server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://home/bkable/workspace/config/

management:
  security:
    enabled: false

